import type { MLModel } from '../types/ml';

export const ML_MODELS: MLModel[] = [
  {
    id: 1,
    name: 'Regresión Lineal',
    algorithm: 'Linear Regression',
    description: 'Predice el rendimiento académico basado en el uso de redes sociales, horas de estudio y edad.',
    accuracy: 85,
    use_cases: 'Predicción continua, análisis de tendencias',
    use_cases_list: ['Predicción continua', 'análisis de tendencias'],
    is_locked: false,
    unlock_condition: 'none',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Regresión Logística',
    algorithm: 'Logistic Regression',
    description: 'Clasifica el riesgo académico en categorías: Alto, Medio y Bajo.',
    accuracy: 82,
    use_cases: 'Clasificación binaria, análisis de riesgo',
    use_cases_list: ['Clasificación binaria', 'análisis de riesgo'],
    is_locked: false,
    unlock_condition: 'none',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'K-Means Clustering',
    algorithm: 'K-Means',
    description: 'Agrupa usuarios con patrones similares de comportamiento en redes sociales.',
    accuracy: 78,
    use_cases: 'Segmentación de usuarios, análisis de grupos',
    use_cases_list: ['Segmentación de usuarios', 'análisis de grupos'],
    is_locked: true,
    unlock_condition: 'complete_form',
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Random Forest',
    algorithm: 'Random Forest',
    description: 'Predicción robusta del rendimiento académico usando múltiples árboles de decisión.',
    accuracy: 89,
    use_cases: 'Predicción compleja, análisis de importancia',
    use_cases_list: ['Predicción compleja', 'análisis de importancia'],
    is_locked: true,
    unlock_condition: 'complete_form',
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Árboles de Decisión',
    algorithm: 'Decision Tree',
    description: 'Genera reglas interpretables para identificar factores de riesgo académico.',
    accuracy: 76,
    use_cases: 'Reglas de negocio, interpretabilidad',
    use_cases_list: ['Reglas de negocio', 'interpretabilidad'],
    is_locked: true,
    unlock_condition: 'complete_form',
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Support Vector Machine',
    algorithm: 'SVM',
    description: 'Clasificación avanzada de patrones de uso problemático en redes sociales.',
    accuracy: 84,
    use_cases: 'Clasificación compleja, detección de patrones',
    use_cases_list: ['Clasificación compleja', 'detección de patrones'],
    is_locked: true,
    unlock_condition: 'complete_form',
    created_at: new Date().toISOString(),
  },
];

export const FORM_OPTIONS = {
  genders: [
    { value: 'Masculino', label: 'Masculino' },
    { value: 'Femenino', label: 'Femenino' },
    { value: 'Otro', label: 'Otro' },
  ],
  educationLevels: [
    { value: 'Bachillerato', label: 'Bachillerato' },
    { value: 'Universidad', label: 'Universidad' },
    { value: 'Posgrado', label: 'Posgrado' },
  ],
  platforms: [
    { value: 'Instagram', label: 'Instagram' },
    { value: 'TikTok', label: 'TikTok' },
    { value: 'Facebook', label: 'Facebook' },
    { value: 'Twitter', label: 'Twitter' },
    { value: 'YouTube', label: 'YouTube' },
    { value: 'LinkedIn', label: 'LinkedIn' },
  ],
};
