import type { MLModel } from "../types/ml";

export const ML_MODELS: MLModel[] = [
  {
    id: 1,
    name: 'Regresión Lineal',
    icon: 'linear-regression',
    algorithm: 'Linear Regression',
    description: 'Predice el rendimiento académico basado en el uso de redes sociales, horas de estudio y edad.',
    accuracy: 85,
    use_cases: "Predicción continua, análisis de tendencias",
    use_cases_list: ["Predicción continua", "análisis de tendencias"],
    is_locked: false,
    unlock_condition: "none",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Regresión Logística',
    icon: 'logistic-regression',
    algorithm: 'Logistic Regression',
    description: 'Clasifica el riesgo académico en categorías: Alto, Medio y Bajo.',
    accuracy: 82,
    use_cases: "Clasificación binaria, análisis de riesgo",
    use_cases_list: ["Clasificación binaria", "análisis de riesgo"],
    is_locked: false,
    unlock_condition: "none",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'K-Means Clustering',
    icon: 'k-means',
    algorithm: 'K-Means',
    description: 'Agrupa usuarios con patrones similares de comportamiento en redes sociales.',
    accuracy: 78,
    use_cases: "Segmentación de usuarios, análisis de grupos",
    use_cases_list: ["Segmentación de usuarios", "análisis de grupos"],
    is_locked: true,
    unlock_condition: "complete_form",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Random Forest',
    icon: 'random-forest',
    algorithm: 'Random Forest',
    description: 'Predicción robusta del rendimiento académico usando múltiples árboles de decisión.',
    accuracy: 89,
    use_cases: "Predicción compleja, análisis de importancia",
    use_cases_list: ["Predicción compleja", "análisis de importancia"],
    is_locked: true,
    unlock_condition: "complete_form",
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Árboles de Decisión',
    icon: 'decision-tree',
    algorithm: 'Decision Tree',
    description: 'Genera reglas interpretables para identificar factores de riesgo académico.',
    accuracy: 76,
    use_cases: "Reglas de negocio, interpretabilidad",
    use_cases_list: ["Reglas de negocio", "interpretabilidad"],
    is_locked: true,
    unlock_condition: "complete_form",
    created_at: new Date().toISOString(),
  },
];
